# 服务配置
server:
  port: 8080

# Spring配置
spring:
  # thymeleaf 配置
  thymeleaf:
    cache: false # 开发时关闭缓存，不然看不到事实时页面
    mode: HTML # 用非严格的HTML
    encoding: utf-8
    servlet:
      content-type: text/html
  # druid 数据源配置
  datasource:
    druid:
      url: jdbc:mysql://59.110.23.184:3306/ask-community?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: fyn12181218.
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  # 加载多个配置文件
  profiles:
    active: redis,email,http

# mybatis 配置
mybatis:
  type-aliases-package: com.feng.community.entity
  mapper-locations: classpath:mapper/*.xml
